networks:
  internal:
    external: false
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bbf
      POSTGRES_DB: bbf
      POSTGRES_PASSWORD: bbf
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/scripts/:/docker-entrypoint-initdb.d/
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 1s
      retries: 500
      start_period: 0s
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: api
      dockerfile: Dockerfile.dev
      args:
        POETRY_VERSION: 2.1.3
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_ENV: dev
      API_PORT: ${API_PORT}
      DB_HOST: db
      DB_USER: bbf
      DB_PASSWORD: /run/secrets/db_secret
      DB_NAME: bbf
      USER_SECRET: /run/secrets/user_secret
    volumes:
      - ./api/src:/app/src
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:$$API_PORT/ || exit 1"]
      interval: 10s
      timeout: 1s
      retries: 100
      start_period: 0s

volumes:
  pgdata:
