networks:
  web:
    external: true
  internal:
    external: false
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.prod
      args:
        POETRY_VERSION: 2.1.3
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_ENV: prod
      API_PORT: ${API_PORT:-8000}
      CLIENT_HOST: ${CLIENT_HOST}
      CLIENT_PROTOCOL: ${CLIENT_PROTOCOL:-https}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: /run/secrets/db_secret
      FROM_EMAIL: ${FROM_EMAIL}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: /run/secrets/smtp_secret
      USER_SECRET: /run/secrets/user_secret
    volumes:
      - ./api/src:/app/src
    secrets:
      - db_secret
      - user_secret
      - smtp_secret
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bbf_api.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.bbf_api.tls=true"
      - "traefik.http.routers.bbf_api.tls.certresolver=lets-encrypt"
      - "traefik.http.services.bbf_api.loadbalancer.server.port=${API_PORT:-8000}"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail ${API_PROTOCOL}://${API_HOST} || exit 1"]
      interval: 10s
      timeout: 1s
      retries: 100
      start_period: 0s
  client:
    depends_on:
      api:
        condition: service_healthy
    build:
      context: client
      dockerfile: Dockerfile.prod
      args:
        CLIENT_PORT: ${CLIENT_PORT:-3000}
        API_PROTOCOL: ${API_PROTOCOL:-https}
        API_HOST: ${API_HOST}
    ports:
      - ${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bbf_client.rule=Host(`${CLIENT_HOST}`)"
      - "traefik.http.routers.bbf_client.tls=true"
      - "traefik.http.routers.bbf_client.tls.certresolver=lets-encrypt"
      - "traefik.http.services.bbf_client.loadbalancer.server.port=${CLIENT_PORT:-3000}"
secrets:
  smtp_secret:
    file: smtp.secret
  db_secret:
    file: db.secret
  user_secret:
    file: user.secret
